### ISSUE TITLE
Dependencies support

### ISSUE THREAD

**Issue by stfp** [kentik/pkg#2]
Support passing dependencies to nfpm with something like:
```
deps:
  deb:
    - libfoo
  rpm:
    - libfoo3
```
